#### general settings
name: Lolv2Real_Oursitself_Stage1_LowerGT_Novgg_1122
use_tb_logger: false
model: enhancement_model
distortion: sr
scale: 1
gpu_ids: [1]
ours_path: /data/huyuxuan/wangwei/papercode_1/AAA1103/Oursitself/experiments/Lolv1_Oursitself_Stage0_1118_CB_SSIM_Color/models/Best_SSIM_Ours.pth
ours_model:
  nf: 64
  nb: 6

#### datasets
datasets:
  train:
    name: ll_dataset
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/train/gt
    dataroot_med: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/train/input
    dataroot_LQ: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/train/input_jpeg

    n_workers: 3  # per GPU
    batch_size: 64
    GT_size: 256   # size you want to crop out as input sample.
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: ll_dataset
    dataroot_GT: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/eval/gt
    dataroot_med: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/eval/input
    dataroot_LQ: /home/huyuxuan/wangwei/datasets/LOL_v2/Real_captured/eval/input_jpeg

#### network structures
network_G:
  which_model_G: FourLLIE
  nf: 16 # 32 # 64

#### path
path:
  root: ./
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  lr_steps: [ 30000,60000,100000, 150000, ]
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0
  val_freq: !!float 2000

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 100000
